# -*- coding: utf-8 -*-
"""MultiAgentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WIW9qvjRtrG8edps6Jd4Gtpj_cPeanNX
"""

# Instalar librerías

!pip install -q mistralai
!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-huggingface
!pip install -q chromadb
!pip install -q sentence-transformers

# Importaciones principales

import pandas as pd
import numpy as np

from google.colab import files
from google.colab import userdata

from mistralai.client import Mistral

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# Configurar API key de Mistral

api_key = userdata.get("MistralProyecto")

client = Mistral(
    api_key=api_key
)

print("API configurada correctamente")

# Test conexión Mistral

respuesta = client.chat.complete(

    model="mistral-small-latest",

    messages=[
        {
            "role":"user",
            "content":"Responde solo: conexión exitosa"
        }
    ]
)

print(respuesta.choices[0].message.content)

# Cargar dataset local

uploaded = files.upload()

archivo = list(uploaded.keys())[0]

df = pd.read_csv(
    archivo
)

print(df.shape)

df.head()

# Explorar información general

print("Dimensiones:")

print(df.shape)

print("\nTipos de datos:")

print(df.dtypes)

print("\nValores nulos:")

print(df.isnull().sum())

# Eliminar customerID porque no aporta al entrenamiento

if "customerID" in df.columns:

    df = df.drop(
        columns=["customerID"]
    )

print("customerID eliminado")

# Convertir TotalCharges a numérico

df["TotalCharges"] = pd.to_numeric(

    df["TotalCharges"],

    errors="coerce"
)

print("Conversión realizada")

# Imputar valores faltantes

df["TotalCharges"] = df["TotalCharges"].fillna(

    df["TotalCharges"].median()
)

print("Valores faltantes corregidos")

# Codificar variables categóricas

encoder = LabelEncoder()

for columna in df.select_dtypes(include="object"):

    df[columna] = encoder.fit_transform(
        df[columna]
    )

print("Variables categóricas codificadas")

# Escalar variables numéricas

scaler = StandardScaler()

columnas_numericas = [

    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

df[columnas_numericas] = scaler.fit_transform(

    df[columnas_numericas]
)

print("Escalado finalizado")

# Verificar dataset limpio

df.head()