# -*- coding: utf-8 -*-
"""MultiAgentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WIW9qvjRtrG8edps6Jd4Gtpj_cPeanNX
"""

# Instalar librerías

!pip install -q mistralai
!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-huggingface
!pip install -q chromadb
!pip install -q sentence-transformers

# Importaciones principales

import pandas as pd
import numpy as np

from google.colab import files
from google.colab import userdata

from mistralai.client import Mistral

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# Configurar API key de Mistral

api_key = userdata.get("MistralProyecto")

client = Mistral(
    api_key=api_key
)

print("API configurada correctamente")

# Test conexión Mistral

respuesta = client.chat.complete(

    model="mistral-small-latest",

    messages=[
        {
            "role":"user",
            "content":"Responde solo: conexión exitosa"
        }
    ]
)

print(respuesta.choices[0].message.content)

# Cargar dataset local

uploaded = files.upload()

archivo = list(uploaded.keys())[0]

df = pd.read_csv(
    archivo
)

print(df.shape)

df.head()