# -*- coding: utf-8 -*-
"""MultiAgentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WIW9qvjRtrG8edps6Jd4Gtpj_cPeanNX
"""

# Instalar librerías

!pip install -q mistralai
!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-huggingface
!pip install -q chromadb
!pip install -q sentence-transformers

# Importaciones principales

import pandas as pd
import numpy as np

from google.colab import files
from google.colab import userdata

from mistralai.client import Mistral

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

# Configurar API key de Mistral

api_key = userdata.get("MistralProyecto")

client = Mistral(
    api_key=api_key
)

print("API configurada correctamente")

# Test conexión Mistral

respuesta = client.chat.complete(

    model="mistral-small-latest",

    messages=[
        {
            "role":"user",
            "content":"Responde solo: conexión exitosa"
        }
    ]
)

print(respuesta.choices[0].message.content)

# Cargar dataset local

uploaded = files.upload()

archivo = list(uploaded.keys())[0]

df = pd.read_csv(
    archivo
)

print(df.shape)

df.head()

# Explorar información general

print("Dimensiones:")

print(df.shape)

print("\nTipos de datos:")

print(df.dtypes)

print("\nValores nulos:")

print(df.isnull().sum())

# Eliminar customerID porque no aporta al entrenamiento

if "customerID" in df.columns:

    df = df.drop(
        columns=["customerID"]
    )

print("customerID eliminado")

# Convertir TotalCharges a numérico

df["TotalCharges"] = pd.to_numeric(

    df["TotalCharges"],

    errors="coerce"
)

print("Conversión realizada")

# Imputar valores faltantes

df["TotalCharges"] = df["TotalCharges"].fillna(

    df["TotalCharges"].median()
)

print("Valores faltantes corregidos")

# Codificar variables categóricas

encoder = LabelEncoder()

for columna in df.select_dtypes(include="object"):

    df[columna] = encoder.fit_transform(
        df[columna]
    )

print("Variables categóricas codificadas")

# Escalar variables numéricas

scaler = StandardScaler()

columnas_numericas = [

    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

df[columnas_numericas] = scaler.fit_transform(

    df[columnas_numericas]
)

print("Escalado finalizado")

# Verificar dataset limpio

df.head()

# Separar variables predictoras y objetivo

X = df.drop(
    columns=["Churn"]
)

y = df["Churn"]

print("Variables separadas")
print(X.shape)

# Dividir entrenamiento y prueba

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y
)

print("División completada")

# Entrenar modelo

modelo = LogisticRegression(

    max_iter=1000
)

modelo.fit(

    X_train,
    y_train
)

print("Modelo entrenado")

# Generar predicciones

predicciones = modelo.predict(

    X_test
)

print("Predicciones generadas")

# Accuracy

accuracy = accuracy_score(

    y_test,
    predicciones
)

print(

    f"Accuracy: {accuracy:.4f}"
)

# Reporte completo

print(

    classification_report(

        y_test,
        predicciones
    )
)

# Agente normalizador

class AgenteNormalizador:

    def invoke(self, dataframe):

        df = dataframe.copy()

        if "customerID" in df.columns:

            df = df.drop(
                columns=["customerID"]
            )

        df["TotalCharges"] = pd.to_numeric(

            df["TotalCharges"],
            errors="coerce"
        )

        df["TotalCharges"] = df["TotalCharges"].fillna(

            df["TotalCharges"].median()
        )

        encoder = LabelEncoder()

        for columna in df.select_dtypes(include="object"):

            df[columna] = encoder.fit_transform(

                df[columna]
            )

        scaler = StandardScaler()

        columnas_numericas = [

            "tenure",
            "MonthlyCharges",
            "TotalCharges"
        ]

        df[columnas_numericas] = scaler.fit_transform(

            df[columnas_numericas]
        )

        return df

# Ejecutar agente

agente_normalizador = AgenteNormalizador()

df_limpio = agente_normalizador.invoke(
    df
)

print(df_limpio.head())

# Agente entrenador

class AgenteEntrenador:

    def invoke(self, dataframe):

        X = dataframe.drop(
            columns=["Churn"]
        )

        y = dataframe["Churn"]

        X_train, X_test, y_train, y_test = train_test_split(

            X,
            y,

            test_size=0.2,

            random_state=42,

            stratify=y
        )

        modelo = LogisticRegression(

            max_iter=1000
        )

        modelo.fit(

            X_train,
            y_train
        )

        predicciones = modelo.predict(

            X_test
        )

        accuracy = accuracy_score(

            y_test,
            predicciones
        )

        metricas = classification_report(

            y_test,
            predicciones,

            output_dict=True
        )

        return {

            "modelo":modelo,

            "accuracy":accuracy,

            "metricas":metricas
        }

# Ejecutar agente entrenador

agente_entrenador = AgenteEntrenador()

resultado = agente_entrenador.invoke(
    df_limpio
)

# Visualizar resultados

print(

    f"Accuracy: {resultado['accuracy']:.4f}"
)

# Mostrar métricas principales

print(

    resultado["metricas"]["weighted avg"]
)

# Agente comunicador

class AgenteComunicador:

    def __init__(self, client):

        self.client = client

    def invoke(self, resultados):

        accuracy = resultados["accuracy"]

        metricas = resultados["metricas"]

        prompt = f"""
        Eres un analista especializado en abandono de clientes.

        Reglas:

        - Usa lenguaje claro.
        - No inventes información.
        - Interpreta clase 0 como:
          Cliente permanece.

        - Interpreta clase 1 como:
          Cliente abandona.

        - Explica:
          Accuracy
          desempeño por clase
          posibles debilidades
          conclusiones

        Accuracy:

        {accuracy}

        Métricas:

        {metricas}
        """

        respuesta = self.client.chat.complete(

            model="mistral-small-latest",

            messages=[

                {
                    "role":"user",
                    "content":prompt
                }

            ]
        )

        return respuesta.choices[0].message.content

# Ejecutar agente comunicador

agente_comunicador = AgenteComunicador(
    client
)

reporte = agente_comunicador.invoke(
    resultado
)

# Mostrar reporte

print(reporte)