# -*- coding: utf-8 -*-
"""CarlosGaleanoProyectoChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQ8Qlw8L0ZCn9NS335a7SnxjWlZa0mvw

# SECCIÓN 1 — Instalación y dependencias

En esta sección instalaremos todas las librerías necesarias para:

- análisis de datos
- manipulación de DataFrames
- conexión con Mistral AI
- creación de agentes con LangChain
"""

# Instalación de librerías principales

!pip install -q \
pandas \
numpy \
matplotlib \
seaborn \
mistralai \
langchain \
langchain-community \
langchain-experimental \
langchain-mistralai \
tabulate

# Verificación de instalación

print("Librerías instaladas correctamente")

"""# SECCIÓN 2 — Importaciones

En esta sección importaremos todas las librerías necesarias para:

- manipulación de datos
- visualización
- conexión con Mistral
- creación del agente pandas
"""

# Importaciones principales

# Manipulación de datos
import pandas as pd
import numpy as np

# Visualización
import matplotlib.pyplot as plt
import seaborn as sns

# Manejo de tiempo y sistema
import os
import warnings

# Mistral AI
from mistralai.client import Mistral

# LangChain + Mistral
from langchain_mistralai import ChatMistralAI

# Agente pandas
from langchain_experimental.agents.agent_toolkits import (
    create_pandas_dataframe_agent
)

# Configuración visual
warnings.filterwarnings("ignore")

print("Importaciones realizadas correctamente")

"""# SECCIÓN 3 — Configuración de API Key

En esta sección configuraremos nuestra API Key de Mistral AI utilizando Google Colab Secrets.

Esto permite:
- mayor seguridad
- evitar exponer credenciales
- mantener el notebook limpio
"""

# Configuración segura de API Key

from google.colab import userdata

# Obtener API Key desde Colab Secrets
api_key = userdata.get("MistralProyecto")

# Guardar temporalmente en entorno
os.environ["MISTRAL_API_KEY"] = api_key

print("API Key configurada correctamente")

"""# SECCIÓN 4 — Instalación de Mistral y test de conexión

En esta sección:

- configuraremos el cliente de Mistral
- probaremos la conexión con la API
- realizaremos una generación simple de texto
"""

# Configuración de cliente Mistral

# Crear cliente oficial de Mistral
client = Mistral(api_key=api_key)

print("Cliente Mistral configurado correctamente")

# Test simple de generación de texto
response = client.chat.complete(
    model="mistral-small-latest",
    messages=[
        {
            "role": "user",
            "content": "Explain briefly what Artificial Intelligence is."
        }
    ]
)

# Mostrar respuesta
print("\nRespuesta del modelo:\n")

print(response.choices[0].message.content)

"""# SECCIÓN 5 — Carga del dataset CSV

En esta sección:

- cargaremos el archivo CSV
- verificaremos que el dataset se lea correctamente
- almacenaremos el DataFrame principal
"""

# Carga interactiva del dataset

from google.colab import files

# Subir archivo CSV manualmente
uploaded = files.upload()

# Obtener nombre del archivo

nombre_archivo = list(uploaded.keys())[0]

print(f"Archivo cargado: {nombre_archivo}")

# Leer dataset

df = pd.read_csv(nombre_archivo, encoding="latin1")

# Vista previa del dataset

print("\nPrimeras filas del dataset:\n")

df.head()

"""# SECCIÓN 6 — Normalización del dataset

En esta sección:

- normalizaremos nombres de columnas
- verificaremos valores nulos
- analizaremos tipos de datos
- eliminaremos duplicados
- generaremos estadísticas generales
- guardaremos un nuevo CSV limpio

IMPORTANTE:

A partir de este punto trabajaremos únicamente
con el dataset normalizado.
"""

# Copia de seguridad del dataset original
df_original = df.copy()

# Normalización de nombres de columnas
df.columns = (
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
)

print("Columnas normalizadas:\n")

print(df.columns.tolist())

# Verificación de valores nulos
print("\nValores nulos por columna:\n")

print(df.isnull().sum())

# Eliminación de duplicados
duplicados_antes = df.duplicated().sum()

df = df.drop_duplicates()

duplicados_despues = df.duplicated().sum()

print(f"\nDuplicados eliminados: {duplicados_antes - duplicados_despues}")

# Tipos de datos
print("\nTipos de datos:\n")

print(df.dtypes)

# Estadísticas generales
print("\nEstadísticas generales:\n")

print(df.describe(include="all"))

# Guardar dataset limpio
nombre_csv_limpio = "ventas_limpio.csv"

df.to_csv(nombre_csv_limpio, index=False)

print(f"\nDataset limpio guardado como: {nombre_csv_limpio}")

# Recargar dataset limpio
df = pd.read_csv(nombre_csv_limpio)

print("\nDataset limpio recargado correctamente")

# Vista previa final
df.head()

"""# SECCIÓN 7 — Creación del agente pandas

En esta sección:

- configuraremos el modelo Mistral Small
- crearemos un agente pandas con LangChain
- habilitaremos tool-calling
- prepararemos el sistema para responder preguntas sobre el CSV

IMPORTANTE:

El agente utilizará el DataFrame limpio como fuente principal de información.
"""

# Configuración del modelo Mistral
llm = ChatMistralAI(
    model="mistral-small-latest",
    mistral_api_key=api_key,
    temperature=0
)

print("Modelo Mistral configurado correctamente")


# Prompt de comportamiento del agente
prefix = """
Eres un asistente especializado en análisis de datos.
Trabjas con un DataFrame que tiene estas Columnas:
- ORDERNUMBER: numero de orden
- QUANTITYORDERED: cantidad de productos pedidos
- PRICEEACH: precio por unidad
- ORDERLINENUMBER: numero de linea de la orden
- SALES: ventas totales
- ORDERDATE: fecha de la orden
- STATUS: estado de la orden
- PRODUCTLINE: linea de producto
- CITY: ciudad
- STATE: estado
- POSTALCODE: codigo postal
- COUNTRY: pais
- TERRITORY: territorio
- CONTACTLASTNAME: apellido de contacto
- CONTACTFIRSTNAME: nombre de contacto
- DEALSIZE: tamaño de la orden
Debes:
- responder únicamente utilizando el DataFrame
- responder siempre en español
- evitar inventar información
- realizar cálculos reales usando pandas
- ser preciso y breve
- Si no podes responder, decilo claramente
"""

# Creación del agente pandas
agent = create_pandas_dataframe_agent(
    llm=llm,
    df=df,
    agent_type="tool-calling",
    verbose=True,
    allow_dangerous_code=True,
    prefix=prefix
)

print("\nAgente pandas creado correctamente")

"""# SECCIÓN 8 — Pruebas y preguntas al agente

En esta sección realizaremos pruebas reales con el agente pandas.

El objetivo es validar que:

- el agente pueda leer el DataFrame
- responda correctamente en español
- utilice pandas internamente
- evite alucinaciones
"""

# Primera prueba simple
pregunta = "¿Cuántas filas y columnas tiene el dataset?"

respuesta = agent.invoke(pregunta)

print("\nRespuesta del agente:\n")

print(respuesta["output"])

# Segunda prueba
pregunta = "¿Cuáles son las columnas del dataset?"

respuesta = agent.invoke(pregunta)

print("\nRespuesta del agente:\n")

print(respuesta["output"])

# Tercera prueba
pregunta = "¿Qué país tiene la mayor cantidad de ventas?"

respuesta = agent.invoke(pregunta)

print("\nRespuesta del agente:\n")

print(respuesta["output"])

# Cuarta prueba
pregunta = "Muéstrame las primeras 5 filas del dataset"

respuesta = agent.invoke(pregunta)

print("\nRespuesta del agente:\n")

print(respuesta["output"])

"""# SECCIÓN 9 — Instalación de librerías RAG

En esta sección instalaremos las librerías necesarias para construir el sistema RAG.

Estas librerías permitirán:

- crear documentos
- generar embeddings
- almacenar vectores en ChromaDB
- realizar retrieval semántico
- conectar Mistral con LangChain
"""

# Instalación de librerías RAG

!pip install -q \
langchain==0.3.27 \
langchain-core==0.3.72 \
langchain-community==0.3.27 \
langchain-text-splitters==0.3.9 \
langchain-chroma==0.2.5 \
langchain-huggingface==0.3.1 \
chromadb==1.0.15 \
sentence-transformers==5.0.0 \
opentelemetry-api==1.38.0 \
opentelemetry-sdk==1.38.0

# Importaciones principales para RAG

# Documento base
from langchain_core.documents import Document

# División de texto
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Embeddings HuggingFace
from langchain_huggingface import HuggingFaceEmbeddings

# Base vectorial ChromaDB
from langchain_chroma import Chroma

# Prompt templates
from langchain_core.prompts import PromptTemplate

# Pipeline RAG
from langchain.chains import RetrievalQA

print("Librerías RAG instaladas correctamente")

"""# SECCIÓN 10 — Creación de documentos semánticos

En esta sección transformaremos cada fila del CSV
en documentos semánticos compatibles con RAG.

Estos documentos serán utilizados para:

- generar embeddings
- almacenar contexto en ChromaDB
- realizar retrieval semántico
"""

# Creación de documentos semánticos

documentos = []

for _, row in df.iterrows():

    contenido = f"""

    Número de orden: {row.get('ordernumber', '')}
    Cantidad pedida: {row.get('quantityordered', '')}
    Precio por unidad: {row.get('priceeach', '')}
    Línea de orden: {row.get('orderlinenumber', '')}
    Ventas totales: {row.get('sales', '')}
    Fecha de orden: {row.get('orderdate', '')}
    Estado de orden: {row.get('status', '')}
    Línea de producto: {row.get('productline', '')}
    Ciudad: {row.get('city', '')}
    Estado/Provincia: {row.get('state', '')}
    Código postal: {row.get('postalcode', '')}
    País: {row.get('country', '')}
    Territorio: {row.get('territory', '')}
    Apellido de contacto: {row.get('contactlastname', '')}
    Nombre de contacto: {row.get('contactfirstname', '')}
    Tamaño de orden: {row.get('dealsize', '')}

    """

    documentos.append(
        Document(page_content=contenido)
    )

print(f"Documentos creados correctamente: {len(documentos)}")

# Vista previa de un documento
print("\nPrimer documento generado:\n")

print(documentos[0].page_content)

"""# SECCIÓN 11 — División de documentos y embeddings

En esta sección:

- dividiremos los documentos en chunks
- cargaremos el modelo de embeddings
- transformaremos texto en vectores numéricos

Estos embeddings permitirán realizar
búsquedas semánticas dentro del sistema RAG.
"""

# ==========================================
# División de documentos en chunks
# ==========================================

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

docs = text_splitter.split_documents(documentos)

print(f"Chunks generados: {len(docs)}")


# ==========================================
# Vista previa de un chunk
# ==========================================

print("\nPrimer chunk:\n")

print(docs[0].page_content)


# ==========================================
# Función para embeddings con Mistral
# ==========================================

def generar_embedding(texto):

    response = client.embeddings.create(
        model="mistral-embed",
        inputs=[texto]
    )

    return response.data[0].embedding


# ==========================================
# Prueba de embedding
# ==========================================

texto_prueba = docs[0].page_content

vector_prueba = generar_embedding(texto_prueba)

print(f"\nDimensión del embedding: {len(vector_prueba)}")


# ==========================================
# Vista parcial del vector
# ==========================================

print("\nPrimeros valores del embedding:\n")

print(vector_prueba[:10])

"""# SECCIÓN 12 — ChromaDB y sistema RAG

En esta sección:

- crearemos la base vectorial ChromaDB
- configuraremos el retriever
- construiremos el prompt del sistema RAG
- conectaremos Mistral con retrieval
- crearemos el pipeline final de consultas
"""

# ==========================================
# Wrapper optimizado para embeddings Mistral
# ==========================================

import time

class MistralEmbeddingFunction:

    def embed_documents(self, texts):

        embeddings = []

        batch_size = 20

        for i in range(0, len(texts), batch_size):

            batch = texts[i:i + batch_size]

            try:

                response = client.embeddings.create(
                    model="mistral-embed",
                    inputs=batch
                )

                batch_embeddings = [
                    item.embedding
                    for item in response.data
                ]

                embeddings.extend(batch_embeddings)

                print(f"Lote procesado: {i + len(batch)}/{len(texts)}")

                # pausa anti rate-limit
                time.sleep(1)

            except Exception as e:

                print(f"Error en lote: {e}")

                # espera extra si ocurre rate limit
                time.sleep(5)

        return embeddings


    def embed_query(self, text):

        response = client.embeddings.create(
            model="mistral-embed",
            inputs=[text]
        )

        return response.data[0].embedding


# ==========================================
# Inicializar embeddings
# ==========================================

embedding_function = MistralEmbeddingFunction()

print("Embedding function configurada")


# ==========================================
# Crear ChromaDB
# ==========================================

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embedding_function,
    persist_directory="./chroma_db"
)

print("ChromaDB creada correctamente")


# ==========================================
# Configuración del retriever
# ==========================================

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 3}
)

print("Retriever configurado")


# ==========================================
# Prompt del sistema RAG
# ==========================================

prompt_template = """

Eres un asistente especializado en análisis de datos de ventas.

Trabajas con un DataFrame que contiene las siguientes columnas:

- ORDERNUMBER: número de orden
- QUANTITYORDERED: cantidad de productos pedidos
- PRICEEACH: precio por unidad
- ORDERLINENUMBER: número de línea de la orden
- SALES: ventas totales
- ORDERDATE: fecha de la orden
- STATUS: estado de la orden
- PRODUCTLINE: línea de producto
- CITY: ciudad
- STATE: estado
- POSTALCODE: código postal
- COUNTRY: país
- TERRITORY: territorio
- CONTACTLASTNAME: apellido del contacto
- CONTACTFIRSTNAME: nombre del contacto
- DEALSIZE: tamaño de la orden

Debes:
- responder únicamente utilizando el contexto proporcionado
- responder siempre en español
- no inventar información
- ser preciso y breve
- si no encuentras la respuesta, indícalo claramente

Contexto:
{context}

Pregunta:
{question}

Respuesta:
"""

PROMPT = PromptTemplate(
    template=prompt_template,
    input_variables=["context", "question"]
)

print("Prompt configurado")


# ==========================================
# Configuración del modelo Mistral
# ==========================================

llm = ChatMistralAI(
    model="mistral-small-latest",
    mistral_api_key=api_key,
    temperature=0
)

print("LLM configurado")


# ==========================================
# Crear sistema RAG
# ==========================================

rag_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    chain_type="stuff",
    chain_type_kwargs={
        "prompt": PROMPT
    }
)

print("Sistema RAG creado correctamente")

"""# SECCIÓN 13 — Consultas al sistema RAG

En esta sección realizaremos las primeras pruebas
del sistema RAG.

El objetivo es verificar:

- retrieval semántico
- comprensión del contexto
- respuestas en español
- reducción de alucinaciones
- funcionamiento completo del pipeline
"""

# ==========================================
# Primera consulta simple
# ==========================================

pregunta = "¿Cuál es el país con más ventas?"

respuesta = rag_chain.invoke(
    {"query": pregunta}
)

print("\nPregunta:")
print(pregunta)

print("\nRespuesta:")
print(respuesta["result"])


# ==========================================
# Segunda consulta
# ==========================================

pregunta = "¿Qué línea de producto generó más ventas?"

respuesta = rag_chain.invoke(
    {"query": pregunta}
)

print("\nPregunta:")
print(pregunta)

print("\nRespuesta:")
print(respuesta["result"])


# ==========================================
# Tercera consulta
# ==========================================

pregunta = "¿Qué ciudad aparece más veces en las órdenes?"

respuesta = rag_chain.invoke(
    {"query": pregunta}
)

print("\nPregunta:")
print(pregunta)

print("\nRespuesta:")
print(respuesta["result"])

# ==========================================
# Chat interactivo RAG
# ==========================================

while True:

    pregunta = input("\nPregunta: ")

    if pregunta.lower() == "salir":
        break

    respuesta = rag_chain.invoke(
        {"query": pregunta}
    )

    print("\nRespuesta:")
    print(respuesta["result"])